### PR TITLE
Another go on "Solve renaming issues with special characters"

### PR DESCRIPTION
**Pull request by jwikman**
It's a challenge to create a regex that matches all possible names of objects. 
Now I've added all printable ASCII characters except ". That should work for files converted from C/AL, but could still miss some Unicode characters if used... Don't really know how to solve that properly.

Anyway, I added a bit to your new test to also check that some characters as µ and åäö still exists after fixing filename.

The test runs fine for me now.

What do you think?

### CODE REVIEW

**Comment by waldo1001** [comment]
It does error out for me :(.
image
I'm having a closer look..

**Comment by jwikman** [comment]
Strange. Let me know what your debugging comes up with.

**Comment by waldo1001** [comment]
Seems that the  ObjectNamePattern doesn't mach with the object name.  I tested that with regexr.com
image

This results in an "no match", so it's not able to "decompile" into a NAVObject.  So my guess is to extend that pattern to allow any character... So something like this:
image

This seems to fix my test, but I'm not sure this is what you agree with :-).  

I'll have to hop on a plane now - can you check?

I like your approach better with these variables though - so I really want this in ;-).

**Comment by jwikman** [comment]
It must have been some issues with your merge, I changed the ObjectNamePattern in this PR compared to the first one, but your screenshot looks like the first PR. Check out the "Changes" on this PR and you'll see. I'm mobile right now, so not able to add a decent screenshot. 😉

I don't think that a .* pattern results in any good. It passes this test, but I'm sure that it will match a lot of unwanted results as well. I created a pattern that matches all printable ASCII characters except ".

Fly safe, and let me know when you've tested with this new pattern. 🙂

**Comment by jwikman** [comment]
Now I'm at a computer again... 

I changed the ObjectNamePattern in NAVObject.ts in this PR:
image

And a test on regexr.com show that it works pretty well on the test object:
image

At least one scenario that might fail is if someone got some a couple of " in the object names... 

If a name is not matched, we might want to throw a more user friendly error... Ie. if currObject = null -> Error(The name xxxx is not allowed) or something similar. The "null reference"-ish error is a bit too non informative... The error should point the user to what file is causing issues.

**Comment by jwikman** [comment]
@waldo1001 I think I have done the object name pattern a bit too complicated!

What about this simple pattern:
image

**Comment by jwikman** [comment]
Sorry to spam this PR, @waldo1001. 
But now I'm happy with how it works for me anyway. 
Added test for object names containing ". 
Also shows user friendly messages/errormessages for the "Reorganize All" and "Rename All" actions.

I will not do more on this now, if you don't say otherwise.

**Comment by waldo1001** [comment]
No problem :) - sorry for not having time to look at it - quite busy in Dubai at the moment.. .  And I want to give it the attention it deserves - one of these days, I'm certainly going to check it out!

**Comment by jwikman** [comment]
No worries. 

I've been able to reorganize my project now, so I'm happy. Look into this when you've got time to, no rush 🙂

Enjoy Dubai!

**Pull request merged**
