### PR TITLE
Solve renaming issues with special characters

### PR DESCRIPTION
**Pull request by jwikman**
I got a lot of errors when using the renaming/reorganize feature on our solution. It seems as all comes down to issues with special characters.

Several issues that I'm trying to solve here:
1. Several special characters not supported
2. Object names is only surrounded with " if needed
3. Objects gets renamed if containing some illegal characters, even though only file needs that. I want object name to remain.

I've tried to solve above issues, and it now runs fine on my 600+ objects. I might have missed some special characters, but at least they only need to be added on one place now.

I have not changed the naming of profile and pagecustomization, since I had not test objects for those, but probably the same change could be done there.

### CODE REVIEW

**Comment by jwikman** [comment]
Btw, a great extension @waldo1001 ! :)

These kind of feedback mostly have a negative sound to it, but it's in it's nature I guess...

**Comment by waldo1001** [comment]
Thanks so much for this, Johannes!  Let me merge and see if it works ;-)

**Comment by waldo1001** [comment]
@jwikman ,

I had to revert the pullrequest, sorry. I couldn't get it to work.

But I did one thing: I created a test in this commit: https://github.com/CloudReadySoftware/crs-al-language-extension/commit/35ec618ba458c71c3266e4bf7d7c91b7636bc3de

If you update your fork, can you run against those tests?  In the meantime, I'll see what I can do to fix it - it seems you did quite a rework on the regex :-) - and it's complicated to decently test it, because of the escape characters :(.

**Comment by jwikman** [comment]
Ok, I see. What test did fail for you?

I didn't really understand how to run your tests, but I'll try to figure that out. I'm pretty darn new to VS Code extensions ;)

What do you think of my change to not change the Object Name if it contains special characters? I mean, the special characters are only a real problem in file naming since they are OK in NAV object names. 

It's always a challenge to interpret regex from others, I took what I've been using in other PowerShell scripts... But if you let me know what fails and not, I might be able to polish them a bit :)

**Pull request merged**
